name: Run TikTok Agent

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_NAME: postgres 
      DB_USER: postgres.qeqlcikxfougmgahwyit 
      DB_PASSWORD: yFSxgm$Y3b@@F.G
      DB_HOST: aws-0-us-east-2.pooler.supabase.com
      DB_PORT: 5432
      PROXY_USER: nuqezlxh
      PROXY_PASS: 7ttdt3buwe0p


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tiktok_requirements.txt

      - name: Install system dependencies for Playwright  
        run: npx playwright install-deps
          
      - name: Install Playwright browsers with deps
        run: playwright install --with-deps

      - name: Run the TikTok script
        run: python tiktok_script.py

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-output
          path: tiktok_trending_cleaned.json  
